network:
  version: 2
  renderer: networkd
  ethernets:
    @@NIC@@:
      dhcp4: false
      dhcp6: false
      accept-ra: false
      link-local: []
  vlans:
    vlan4: {id: 4, link: @@NIC@@, dhcp6: false, accept-ra: false, link-local: []}
    vlan5: {id: 5, link: @@NIC@@, dhcp6: false, accept-ra: false, link-local: []}
  bridges:
    br-mgmt:
      interfaces: [@@NIC@@]
      addresses: [192.168.3.10/24]
      routes: [{to: default, via: 192.168.3.1}]
      nameservers: {addresses: [@@DNS1@@, @@DNS2@@]}
      dhcp6: false
      accept-ra: false
      link-local: []
      parameters: {stp: false, forward-delay: 0}
    br-game:
      interfaces: [vlan4]
      dhcp6: false
      accept-ra: false
      link-local: []
      parameters: {stp: false, forward-delay: 0}
    br-svc:
      interfaces: [vlan5]
      dhcp6: false
      accept-ra: false
      link-local: []
      parameters: {stp: false, forward-delay: 0}
