# Fichier: 60-harmonisation.conf
# Emplacement: Project_homeserver/nas/rsyslog/60-harmonisation.conf
# Langage: configuration rsyslog (RainerScript)
# Role: reçoit les logs de toutes les sources sur le port UDP 1514, déduit une sévérité,
#       et réécrit chaque ligne dans un format unique harmonisé.

module(load="imudp")

input(type="imudp" port="1514" ruleset="harmonisation")

template(name="FormatUnifie" type="string"
  string="%timestamp:::date-rfc3339% - [%$.sev%] %programname% : %msg%\n")
  
ruleset(name="harmonisation") {
    if ($programname == "CrowdSec" and $msg contains "banned") then {
        set $.sev = "DANGER";
    } else if ($programname == "Firewall-i5" and $msg contains "UFW BLOCK") then {
        set $.sev = "ALERTE";
    } else if ($programname == "ER605" and $msg contains "Attack Defense") then {
        set $.sev = "ALERTE";
    } else if ($programname == "psad" and $msg contains "DL: 4") then {
        set $.sev = "ALERTE";
    } else if ($programname == "psad" and $msg contains "DL: 5") then {
        set $.sev = "DANGER";
    } else {
        set $.sev = "INFO";
    }
	
    action(type="omfile" file="/var/log/harmonise/harmonise.log" template="FormatUnifie")
	
    # action(type="omfwd" target="127.0.0.1" port="514" protocol="udp" template="FormatUnifie")
	
    # ^ ligne désactivée pour l'instant : renverra vers le vrai NAS en Phase 7
}

