action(type="omfwd" target="192.168.5.10" port="1514"
  protocol="tcp" template="RSYSLOG_SyslogProtocol23Format"
  action.resumeRetryCount="-1"
  queue.type="LinkedList" queue.filename="Home_server-transfert"
  queue.maxDiskSpace="128m" queue.saveOnShutdown="on")
