module(load="imfile")
input(type="imfile" File="/var/log/nginx/access.log"
  Tag="nginx-access:" Severity="info" Facility="local6"
  PersistStateInterval="100" Ruleset="Home_server_harmoniser")
input(type="imfile" File="/var/log/nginx/error.log"
  Tag="nginx-error:" Severity="warning" Facility="local6"
  PersistStateInterval="100" Ruleset="Home_server_harmoniser")
input(type="imfile" File="/var/log/crowdsec.log"
  Tag="crowdsec:" Severity="info" Facility="local6"
  PersistStateInterval="100" Ruleset="Home_server_harmoniser")
input(type="imfile" File="/var/log/crowdsec-firewall-bouncer.log"
  Tag="crowdsec-bouncer:" Severity="info" Facility="local6"
  PersistStateInterval="100" Ruleset="Home_server_harmoniser")
